# Generated by Django 2.1.7 on 2019-03-13 21:36

from django.db import migrations

def setcurrent(apps, schema_editor):
    Match = apps.get_model('regame', 'Match')
    for row in Match.objects.all():
        row.current = row.player2
        row.save(update_fields=['current'])

def dropcurrent(apps, schema_editor):
    Match = apps.get_model('regame', 'Match')
    for row in Match.objects.all():
        row.current = None
        row.save(update_fields=['current'])

class Migration(migrations.Migration):

    dependencies = [
        ('regame', '0002_auto_20190313_2135'),
    ]

    operations = [
        migrations.RunPython(setcurrent, reverse_code=dropcurrent),
    ]
