# Generated by Django 2.1.7 on 2019-03-13 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regame', '0003_auto_20190313_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_current_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
