# Generated by Django 2.1.7 on 2019-03-14 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regame', '0004_auto_20190313_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possessedcard',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='regame.Card'),
        ),
    ]
