# Generated by Django 2.1.7 on 2019-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regame', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastseen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
