# Generated by Django 2.1.7 on 2019-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regame', '0009_userprofile_lastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
