# Generated by Django 2.1.7 on 2019-03-25 18:48

from django.db import migrations
import enumfields.fields
import regame.models


def setstatus(apps, schema_editor):
    Match = apps.get_model('regame', 'Match')
    for match in Match.objects.all():
        match.status = (regame.models.MatchStatus.PENDING
                        if match.active else
                        regame.models.MatchStatus.ENDED)
        match.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('regame', '0011_auto_20190325_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=enumfields.fields.EnumField(default='f', enum=regame.models.MatchStatus, max_length=1),
        ),
        migrations.RunPython(setstatus),
        migrations.RemoveField(
            model_name='match',
            name='active',
        ),
    ]
