# Generated by Django 2.1.7 on 2019-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regame', '0012_auto_20190325_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winconditionnumber',
            field=models.PositiveSmallIntegerField(default=21),
        ),
    ]
