# Generated by Django 2.1.7 on 2019-04-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def generateparticipants(apps, schema_editor):
    Match = apps.get_model('regame', 'Match')
    MatchParticipant = apps.get_model('regame', 'MatchParticipant')
    participants = []
    for match in Match.objects.all():
        participants.append(MatchParticipant(
            match=match,
            player=match.player1,
            index=0,
            score=match.player1score
        ))
        participants.append(MatchParticipant(
            match=match,
            player=match.player2,
            index=1,
            score=match.player2score
        ))
    MatchParticipant.objects.bulk_create(participants)


def fillparticipantofcard(apps, schema_editor):
    PossessedCard = apps.get_model('regame', 'PossessedCard')
    for card in PossessedCard.objects.all():
        card.participant = card.match.participants.get(player=card.player)
        card.save(update_fields=['participant'])


def setcurrentparticipant(apps, schema_editor):
    Match = apps.get_model('regame', 'Match')
    for match in Match.objects.all():
        match.currentparticipant = match.participants.get(player=match.current).index
        match.save(update_fields=['currentparticipant'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regame', '0013_auto_20190326_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('score', models.IntegerField(default=0)),
                ('activity', models.TextField()),
                ('chat', models.CharField(max_length=200)),
                ('drawoffer', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='currentparticipant',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='regame.Match'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possessedcard',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='regame.MatchParticipant'),
        ),
        migrations.RunPython(generateparticipants),
        migrations.RunPython(fillparticipantofcard),
        migrations.RunPython(setcurrentparticipant),
    ]
