# Generated by Django 2.1.7 on 2019-04-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regame', '0014_auto_20190402_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='current',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2score',
        ),
        migrations.RemoveField(
            model_name='possessedcard',
            name='match',
        ),
        migrations.RemoveField(
            model_name='possessedcard',
            name='player',
        ),
    ]
